/*
 * This source file was generated by the Gradle 'init' task
 */
package git;

public class App {
    public String getGreeting() {
        return "Hello Object Oriented Programming!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
